version: "3.8"
services:
  jenkins:
    build: .
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - ~/.aws:/home/jenkins/.aws
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    user: jenkins
volumes:
  jenkins-data:

